### ISSUE TITLE
Generating more faces

### ISSUE THREAD

**Issue by EricCHChang** [unibas-gravis/parametric-face-image-generator#16]
Hi,

I followed the instructions, put necessary files in the data folder and used java -Xmx2g -cp generator.jar faces.apps.ControlledFaces -c data/config_files/example_config_controlled.json to call the program. The program generated sample images of 3 different viewpoints of one facial identity (i.e., the same person), which are found in the folder output/img/0, but then the program stopped without any error messages. I would like to generate more images of different facial identities. Would you please let me know how can I do that?  

Thank you for your help.

Best,
Eric

**Comment by AdamKortylewski** [comment]
Hi Eric,

please take a look at the config file "example_config_controlled.json". You can e.g. increase the number of facial identities to be generated by adjusting the option "number-of-ids-to-create" in line 26.

Best,
Adam
