### ISSUE TITLE
Control similarity between generated facial identities 

### ISSUE THREAD

**Issue by EricCHChang** [unibas-gravis/parametric-face-image-generator#18]
Hi,

I was wondering if it is possible to use this generator to generate a set of faces in which their visual similarities vary in certain ways. For example, given a specific facial identity (target), I want to adjust the parameter of colour or shape to create a set of facial identities that are similar (or very different) to that target.  

Would you please let me know if it is possible, and if so, how can I modify the script to do so?

Thank you so much for your help. 

Best,
Eric

**Comment by BernhardEgger** [comment]
Hi Eric,

that is possible with our scalismo-faces framework. Depending on your application the parametric-face-image-generator is the correct starting point or you perhaps start a separate project based on scalismo-faces. To generate a very different face you can invert the parameters and you get an "anti-face" (compare Blanz Vetter '99 http://gravis.dmi.unibas.ch/publications/Sigg99/morphmod2.pdf).
Best
Bernhard

**Comment by BernhardEgger** [comment]
Hi Eric,

again some thoughts: your ideas sound more in the direction of perception. For me it sounds like an opportunity to provide a data-generator or a setting in that direction. Perhaps you or we could add an additional setting to implement your ideas...

Best
Bernhard

**Comment by EricCHChang** [comment]
Hi Bernhard,

It sounds great, but my concern is that I need a dataset of faces for my project in a few weeks and I have little experience in Java. Do you have a hunch how long it might take to implement additional settings to the scalismo-faces framework to generate faces that meet my requirements?

Thank you.

Best,
Eric

**Comment by BernhardEgger** [comment]
Hi Eric,
it heavily depends what your requirements are - the stuff you sketched above sounds quite easy and straight forward.
The easiest solution might be if we skype.
I then also want to discuss with Adam if we aim to put that in this project or if we should go for a separate one...
Can you send me an email? egger.bernhard@gmail.com
Best
Bernhard
