### ISSUE TITLE
Format of expression ground truth

### ISSUE THREAD

**Issue by ThrupthiAnn** [unibas-gravis/parametric-face-image-generator#24]
Hi

In the rps file, the expression is encoded as a long string of numbers. How do we interpret these numbers? Is there a way to convert them to emotion (valence + arousal)?

**Comment by BernhardEgger** [comment]
Hi ThrupthiAnn,
it is a statistical expression model. The vector of numbers reflects the coefficients of this statistical model. To get emotions out you would need to label some instances and classify accordingly or project expressions into the model.
The expression model is explained here:
https://gravis.dmi.unibas.ch/publications/2018/2018_Gerig_FG18.pdf
Please use our google group for questions like this
https://groups.google.com/forum/#!forum/scalismo-faces
Best
Bernhard
