### ISSUE TITLE
Controling age and gender

### ISSUE THREAD

**Issue by ThrupthiAnn** [unibas-gravis/parametric-face-image-generator#25]
In the Basel Faces 2009 page, it looked like there was an age and gender axis. How do we control age and gender?

**Comment by BernhardEgger** [comment]
Hi ThrupthiAnn,
the Basel Face Model 2009 comes with its own software. The matlab software that was delivered with the BFM 2009 allows manipulation of attributes (but not full control over them). You could add 10 years of age but you don't know the age of the current instance.
Further reading on how this manipulation works:
https://gravis.dmi.unibas.ch/publications/2009/ISVC09_Amberg.pdf
For the Basel Face Model 2017 there are no attributes provided.
One way to integrate attributes directly into the model would be a Copula based model:
https://gravis.dmi.unibas.ch/publications/2017/2017_Copula_Eigenfaces_with_Attributes.pdf
Please use our google group for questions like this
https://groups.google.com/forum/#!forum/scalismo-faces
Best
Bernhard
