### ISSUE TITLE
How to generate same identity faces after each run?

### ISSUE THREAD

**Issue by ilovecv** [unibas-gravis/parametric-face-image-generator#29]
Hi, 

When I run the generator.jar, it will generate faces with different identities after each run. How can I fix the random see to reproduce the results? i.e., for each run of generator, the identities of the generated faces are fixed. Thanks!

**Comment by BernhardEgger** [comment]
Hi,
there is a random seed for all parameters that are sampled. If you run the program twice with the exact same setting it will generate the exact same dataset..
There is no seperate seed for the identity and therefore if you change other settings (like the number of samples per id) the ids will change.
There is however a branch fixID that allows to load an  id (load an rps file) and generate new samples for this id in a new folder (fixedId).
https://github.com/BernhardEgger/parametric-face-image-generator/commit/d5b46a25f12bc6aec80657afca9b74591b5d4184
If you checkout that branch and compile it you can generate new samples per id.

Best
Bernhard
