### ISSUE TITLE
rebuild

### ISSUE THREAD

**Issue by ReverseSystem001** [unibas-gravis/parametric-face-image-generator#30]
I want to rebuild the parametric-face-image-generator-2.0 and generate a new .tar, because when i run: java -Xmx2g -cp generator.jar faces.apps.ControlledFaces -c data/config_files/example_config_controlled.json, there is something wrong like below:(I set the parameter number-of-ids-to-create:3 in morphable-model-parameters)
_files/example_config_controlled.json
Generating 	 ID:1 	 Sample:1
Generating 	 ID:0 	 Sample:1
Generating 	 ID:2 	 Sample:1
Something went wrong with id: 2
None.get
[Ljava.lang.StackTraceElement;@6356fc26
Something went wrong with id: 1
None.get
Something went wrong with id: 0
None.get
[Ljava.lang.StackTraceElement;@60c3eb97
[Ljava.lang.StackTraceElement;@452ac960

**Comment by BernhardEgger** [comment]
Hi
Can you please check if you downloaded all dependencies in the data folder?
Best
Bernhard

**Comment by ReverseSystem001** [comment]
thanks for your reply. According to usage. i download model2017-1_face12_nomouth.h5 and put it in bfm2017 file. download  Basel Illumination Prior 2017 and put the parameters into the bip file. I didn't get a dataset with backgrounds. so when i run: java -Xmx2g -cp generator.jar faces.apps.ControlledFaces -c data/config_files/example_config_controlled.json.  i set the parameters  "insert-background-image": false. like below. 
 "backgrounds": {
    "insert-background-image": false,
    "background-images-directory": "data/backgrounds/",
    "background-image-extension": ".jpg"
  }
  "morphable-model-parameters": {
    "number-of-ids-to-create": 3,
    "number-of-samples-per-id": 3,
    "model-filename": "data/bfm2017/model2017-1_face12_nomouth.h5",
    "__comment-1" : "A value of 0 for any dimension will return always the mean for this dimension",
    "dimension-of-shape-space": 199,
    "dimension-of-color-space": 199,
    "dimension-of-expression-space": 100,
    "add-expressions": false
  }
What else do I need to download??? thks
