### ISSUE TITLE
How to generate a face with closed eye

### ISSUE THREAD

**Issue by zhongtao93** [unibas-gravis/parametric-face-image-generator#34]
Since we know that there is  no close eye expression in BFM, so how to generate a face with closed eye?

Thank you for sharing code!

**Comment by Andreas-Forster** [comment]
I am unaware of code doing that.

The BFM does not model the eyeball independently, but it is connected to the eyelids. This can be changed in any 3d modeler software. Further, you would then need to come up with the deformations that close the eyelid such that it stays on top of the eyeball.

**Comment by zhongtao93** [comment]
Yes, that means need a addtional 3d modeler software or other deformations code. 

So in this project the  close eye face can't be generated if only shuffling those expression parametric randomly. 

It will be in the works that support to generate close eye face in the furture?

**Comment by Andreas-Forster** [comment]
We are an open source project and welcome contributions.

To the best of my knowledge I don't know of any current development for 
this project on this topic.


Am 6/3/2020 um 10:25 AM schrieb Tao Zhong:

**Comment by zhongtao93** [comment]
Ok, thanks. I'll contribute my work if I made some progress on this topic.
