### ISSUE TITLE
Landmark tags

### ISSUE THREAD

**Issue by ahmetbayirli** [unibas-gravis/parametric-face-image-generator#37]
Hi, 
I need the complete list of landmark tags. I couldn't find them. Reading codes, BFM files, etc, so far I got these ones;

center.chin.tip
center.lips.lower.inner
center.nose.tip
center.front.trichion
left.ear.lobule.attachement
left.ear.helix.outer
right.ear.lobule.attachement
right.ear.helix.outer
left.eye.corner_outer
left.eye.corner_inner
left.eye.pupil.center

right.eye.corner_outer
right.eye.corner_inner
right.eye.pupil.center
left.eyebrow.bend.lower

left.eyebrow.inner_lower
right.eyebrow.bend.lower
right.eyebrow.inner_lower
left.lips.corner

right.lips.corner
left.nose.wing.tip
right.nose.wing.tip

What are the others?
..
Thanks in advance.

**Comment by BernhardEgger** [comment]
Hi Ahmet Bayirli,

you can find the complete list of landmarks in the model file:
https://faces.dmi.unibas.ch/bfm/bfm2017.html

here is the json string from the model file:
[{"id":"right.nose.wing.outer","coordinates":[-18.534284591674805,-2.5953829288482666,103.7481918334961],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eye.corner_inner","coordinates":[-20.83174705505371,32.71833801269531,92.38187408447266],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.nose.wing.tip","coordinates":[-15.36320686340332,-7.958990097045898,106.85011291503906],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.lobule.tip","coordinates":[-73.1007080078125,-15.156641960144043,5.376224994659424],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eye.corner_outer","coordinates":[41.6480712890625,32.799415588378906,88.01728057861328],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.lips.lower.inner","coordinates":[0.0,-42.586097717285156,106.57559967041016],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.chin.tip","coordinates":[0.0,-78.85458374023438,96.38277435302734],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.nasolabial_fold.center","coordinates":[-31.107519149780273,-20.735645294189453,98.86211395263672],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eye.corner_outer","coordinates":[-41.6480712890625,32.799415588378906,88.01728057861328],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.lips.philtrum_ridge","coordinates":[5.214076042175293,-23.45208168029785,114.27684783935547],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eyebrow.inner_lower","coordinates":[19.56281089782715,47.490753173828125,104.61712646484375],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.helix.outer","coordinates":[-90.59452056884766,18.187381744384766,-13.684348106384277],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.lips.philtrum_ridge","coordinates":[-5.214076042175293,-23.45208168029785,114.27684783935547],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.lobule.tip","coordinates":[73.1007080078125,-15.156641960144043,5.376224994659424],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.lips.corner","coordinates":[-23.868661880493164,-37.87042236328125,98.44570922851562],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.antihelix.center","coordinates":[-84.30335998535156,7.112959861755371,-5.622922897338867],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.front.trichion","coordinates":[0.0,88.21302032470703,103.1274642944336],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.helix.top","coordinates":[90.90851593017578,39.661277770996094,-0.18586699664592743],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.helix.attachement","coordinates":[79.90679168701172,39.56269073486328,5.256990909576416],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.tragus.tip","coordinates":[-71.76718139648438,6.317695140838623,10.93033218383789],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.tragus.tip","coordinates":[71.76718139648438,6.317695140838623,10.93033218383789],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.antihelix.center","coordinates":[84.30335998535156,7.112959861755371,-5.622922897338867],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eye.corner_inner","coordinates":[20.831750869750977,32.71833801269531,92.38187408447266],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.lobule.center","coordinates":[-73.56227111816406,-12.80288028717041,7.326574802398682],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.lips.lower.outer","coordinates":[0.0,-52.964420318603516,106.97721099853516],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.helix.center","coordinates":[-89.1048812866211,8.76367473602295,-11.864278793334961],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.lips.upper.inner","coordinates":[0.0,-32.59500503540039,109.248046875],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.nasolabial_fold.center","coordinates":[31.107519149780273,-20.735645294189453,98.86211395263672],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.nasolabial_fold.bottom","coordinates":[-32.39739227294922,-40.06598663330078,93.59249114990234],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eye.top","coordinates":[32.07980728149414,33.26529312133789,94.68875122070312],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.helix.center","coordinates":[89.1048812866211,8.76367473602295,-11.864278793334961],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eye.top","coordinates":[-32.07980728149414,33.26529312133789,94.68875122070312],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eyebrow.bend.upper","coordinates":[-46.843570709228516,56.96644973754883,92.22718048095703],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eyebrow.inner_lower","coordinates":[-19.562807083129883,47.490753173828125,104.61712646484375],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.nose.hole.center","coordinates":[8.723098754882812,-9.142240524291992,111.85400390625],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eyebrow.bend.lower","coordinates":[-50.02317810058594,46.903778076171875,90.64554595947266],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.helix.outer","coordinates":[90.59452056884766,18.187381744384766,-13.684348106384277],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.nose.attachement_to_philtrum","coordinates":[0.0,-9.93749713897705,117.9772720336914],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eyebrow.inner_upper","coordinates":[20.86087417602539,55.80046463012695,107.25347137451172],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.lobule.attachement","coordinates":[67.89292907714844,-15.945412635803223,11.362247467041016],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eyebrow.bend.upper","coordinates":[46.843570709228516,56.96644973754883,92.22718048095703],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eyebrow.bend.lower","coordinates":[50.02317810058594,46.903778076171875,90.64554595947266],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.antihelix.tip","coordinates":[72.57823944091797,-4.9602580070495605,8.57014274597168],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.helix.top","coordinates":[-90.90851593017578,39.661277770996094,-0.18586699664592743],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eye.pupil.center","coordinates":[32.03553771972656,36.998172760009766,94.827880859375],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.nose.hole.center","coordinates":[-8.723097801208496,-9.142240524291992,111.85400390625],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.helix.attachement","coordinates":[-79.90679168701172,39.56269073486328,5.256990909576416],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.nose.tip","coordinates":[0.0,1.394950032234192,131.14027404785156],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.nasolabial_fold.bottom","coordinates":[32.39739227294922,-40.06598663330078,93.59249114990234],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eye.bottom","coordinates":[-32.432315826416016,29.563983917236328,93.50888061523438],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.ear.lobule.center","coordinates":[73.56227111816406,-12.80288028717041,7.326574802398682],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.antihelix.tip","coordinates":[-72.57823944091797,-4.9602580070495605,8.57014274597168],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eyebrow.inner_upper","coordinates":[-20.86087417602539,55.80046463012695,107.25347137451172],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"center.lips.upper.outer","coordinates":[0.0,-25.280044555664062,114.79743957519531],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.nose.wing.outer","coordinates":[18.534284591674805,-2.5953829288482666,103.7481918334961],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.nose.wing.tip","coordinates":[15.363207817077637,-7.958990097045898,106.85011291503906],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.lips.corner","coordinates":[23.868663787841797,-37.87042236328125,98.44570922851562],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.ear.lobule.attachement","coordinates":[-67.89292907714844,-15.945412635803223,11.362247467041016],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"right.eye.pupil.center","coordinates":[-32.03553771972656,36.998172760009766,94.827880859375],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}},{"id":"left.eye.bottom","coordinates":[32.432315826416016,29.563983917236328,93.50888061523438],"uncertainty":{"stddevs":[1.0,1.0,1.0],"pcvectors":[[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]]}}]


Best
Bernhard
--
0 1 0
0 0 1
1 1 1
