### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by fisakhan** [unibas-gravis/parametric-face-image-generator#38]
Is there any python implementation of this repo?

**Comment by BernhardEgger** [comment]
I'm not aware of one.
But the jar-executable together with the config files makes it trivial to use
You might find python related sources here:
https://github.com/3d-morphable-models/curated-list-of-awesome-3D-Morphable-Model-software-and-data

and some basic python stuff here:
https://github.com/YadiraF/face3d

Best
Bernhard
