### ISSUE TITLE
Controlled Config files not working

### ISSUE THREAD

**Issue by BernhardEgger** [unibas-gravis/parametric-face-image-generator#9]
For both controlled config files I get the following error:
Exception in thread "main" java.util.NoSuchElementException: key not found: illumination-parameters

**Comment by Andreas-Forster** [comment]
Could you please provide more inforamtion. How did you call the application? What config file did you use?

My first guess would be that you start the RandomFaces app with the ControlledSetting config file.

**Comment by BernhardEgger** [comment]
I did not execute with java -Xmx2g -cp generator.jar faces.apps.ControlledFaces... somehow the error could be smarter, but definitely my fault.
